### ISSUE TITLE
clarify use of forced flag

### ISSUE THREAD

**Issue by mcr** [ietf-wg-cellar/matroska-specification#374]
rebase #158, and adjust text to reflect consensus

**Comment by robUx4** [comment]
Copying the comment from @rcombs so we can continue the discussion here:

Rebased (after a long delay, sorry!); hoping for a bit more discussion. I've just been paging this all back in, and I'm going to dump some thoughts in here:

There are really 4 questions the spec has to answer here; 2 for each of the 2 flags:
- How should players make use of them, for optimal compatibility with the intent of both existing files and new ones?
- How should file authors set them, in order to achieve optimal behavior for users?

And there are a few important caveats to keep in mind:
- These flags are handled in players at a level well above the Matroska demuxer itself. They generally don't implement Matroska-specific behavior for them, and aren't likely to start after a spec change. Anything we recommend here has to be applicable to any format with default or forced flags, and has to provide as good or better a user experience than the ad-hoc behaviors players already have, or it's just going to be ignored.
  - As a corollary, these flags can't invent entirely new types of behavior (like the current "overlay two tracks together" suggestion). Anything unusual and complex like that would need to be defined as a distinct new field.
- Any advice we give file authors on how to use these flags is only going to be followed if doing so results in the behavior those authors want to achieve in the players their target audience uses. If following the spec's advice doesn't do what they want, they'll ignore it and come up with some method that does.

Now, musings on the individual flags:

## The default flag
The "default" flag has always been a little strange, in that if there's only one track with the flag set, it doesn't really provide much value that you can't achieve simply by putting a track first in the list. There are a few possible uses for it (and in practice, usage is inconsistent):
- Indicating which track should be used if there's no language setting
  - Essentially the same as putting the track first
  - Usually would be either a track in the original language, or one in the file author's/primary target audience's
- Indicating which track, out of multiple for a given language, should be used
  - Could be used to indicate a "normal" track, as opposed to a commentary, descriptive audio, forced subtitle, SDH, etc. track; this can have actual value beyond what you get from simple ordering, as it could be used on multiple tracks (e.g. a stereo and a 5.1) to indicate "by default, when selecting a track of this language, pick the one with the default flag set that best matches the output channel layout"
  - Sometimes might refer to a track that the file author considers preferable to others that seem, to a machine, equivalent (e.g. multiple different translations or dubs in the same language); this again isn't much different than putting the recommended one first

In practice both of these uses exist, plenty of files simply don't set a default (or set it on all tracks), and it's somewhat impractical to depend on in player software.

So, I think the best algorithm to recommend for players (for compat with all reasonable cases in existing files as well as new ones), written out in full, is:
- If no audio track matching the user's language preferences is present, select the language of the first audio track with the default flag set, or if none is present, the language of the first audio track.
- If multiple audio tracks matching the chosen language (set either by the user or in the previous step) are present, autoselect between the ones that have the default flag set. If none, use the first of the group.
- If multiple subtitle tracks matching the chosen language (either from the user's preferences or an optional fallback of undefined) are present, select the first one with the default flag set. If none, use the first of the group.

And for advice to file authors:
- Place tracks in the source language before those of the same type in other languages
- Within each group of tracks of the same language and type, place recommended tracks (e.g. preferred translation, dub, source, etc) first.
- Set the default flag on all tracks that you want to be available to autoselection without special circumstances; i.e. non-commentary, non-SDH, non-descriptive, non-forced (all of which have their own additional flags, though SDH doesn't have one in Matroska yet as far as I'm aware)

## The forced flag
In practice, the forced flag has clear meaning, use, and implementation:
- It signals a track that should be played, even if the user's settings normally wouldn't enable subtitles with the selected audio track.
- It's used on tracks containing translations of onscreen text, foreign-language dialogue, music left in the original language in an otherwise-dubbed audio track, or other text that needs to be displayed onscreen even if the user can hear and understand a corresponding audio track.
  - Note that in practice, file authors duplicate this data in both a forced and a regular track, rather than rely on the player to display both the forced track and the regular track.
  - And in practice, players don't implement support for selecting both a forced and a regular track simultaneously and displaying both.
- It's implemented by something along the lines of "when an audio track matching the user's language preferences is selected, autoselect a forced track even if the user doesn't have subtitles turned on for all content by default".

In practice the flag is also used very inconsistently, often on tracks where setting "default" would've made more sense, but usually in ways that aren't especially harmful in practice. My suggestion is that we simply codify that existing player behavior, and recommend that existing usage to file authors.

**Comment by robUx4** [comment]
Some initial comment:

##  default flag
I have a problem with forcing the order of tracks. So far only `TrackOverlay` has this requirement. And that's a feature nobody ever used and may never use at all. The rest of the time, remuxing a file and reordering tracks should produce the same playback experience. That's actually a strong design enforced on muxers that they have to keep track of when they can set in the Track Entry. For example a software that would transcode a file and add tracks in the order they first get their first encoded frame. If we can do without this requirement, the better.

From your explanation, the "pick the first" rule always comes after other options don't fit. So hopefully a properly authored file would not fall in this category.

I think we should have a diagram somewhere explaining the decision of what track to pick when playback starts. Audio and Subtitles are different because when playing a video you surely want audio as well as the video. Subtitles not so much, it's based on user preferences. But you can only tell if you want the subtitle track once you have picked the one you would use (in my case if it's French or English I don't want it, but if it's Korean, I do).

The decision on which language to pick is also based on user preferences. In my case, for audio, I would prefer:
- original
- English or French
- whatever is available

For subtitles my choice would also depend on the audio picked:
- if audio is French or English, no subtitle
- otherwise:
  - French or English
  - nothing

It seems that the `FlagDefault` has little use for subtitles. For audio it would be better to tell which track contains the original language (there can be more than one). So here as well it's useless.

I would be in favor of deprecating it. In the end if set to false the intention is to distinguish from tracks which has the flag set (or not at all) so they are less likely to be picked.

I would really like to have a flag telling an audio or subtitle track is in the original language. That can be really helpful to pick the one to start with. We currently don't have this information (or only in Tags which is not used and shouldn't be used to pick tracks). Alternatively the "source language" could be set in the Segment Information and any Track matching that language would be considered as original. It would probably be more flexible than a flag. For example you could have "fr-ca" as the original language and if no "fr-ca" track is found (has been stripped) you may use "fr" as a good candidate next.

I also agree SDH should have its own flag in the Track Entry.

In VLC the logic to pick tracks (regardless of types is as follow)
```c
        if( unlikely( !track.b_enabled ) )
            track.fmt.i_priority = ES_PRIORITY_NOT_SELECTABLE;
        else if( track.b_forced )
            track.fmt.i_priority = ES_PRIORITY_SELECTABLE_MIN + 2;
        else if( track.b_default )
            track.fmt.i_priority = ES_PRIORITY_SELECTABLE_MIN + 1;
        else
            track.fmt.i_priority = ES_PRIORITY_SELECTABLE_MIN;
```
(if not track of a kind has the default flag set, the first track of that kind gets to have the flag set)

## forced flag
>Note that in practice, file authors duplicate this data in both a forced and a regular track, rather than rely on the player to display both the forced track and the regular track

I wasn't aware of that but if that's the case we could remove the overlay part of the definition (which AFAIK is not implemented anywhere). In that case the forced flag track should only be used if no other track of that kind is already selected. Meaning that it's actually a fall-through if no track is selected by default. (a diagram would help clarify this)

**Comment by rcombs** [comment]
>For example a software that would transcode a file and add tracks in the order they first get their first encoded frame.

I'm not sure this is a _great_ example; the order of the tracks in the file is generally the order displayed to the user in a stream picker, so the author will generally want to curate it. Still, I see your point about not wanting it to be used for autoselection beyond as a fallback.

I agree that the default flag isn't especially useful without a specific purpose assigned to it. My suggestion was that it could be used as a "regular" flag (i.e. not commentary, etc; should participate in autoselection in the absence of other overrides).

I put together a recommended stream selection flow diagram with diagrams.net. It's not 100% complete (for instance, it doesn't have a mechanism for automatically selecting audio-description streams), but it describes how I imagine the flags we've discussed here working. I can figure out how to share the chart itself if anyone's interested in making their own version.
![Stream Selection Flow](https://user-images.githubusercontent.com/819638/82751331-0692a200-9d7c-11ea-83f9-9cbda8d187a8.png)

As a side-note, this also brings up how we should really have some additional stream-disposition flags, particularly around accessibility; in ffmpeg we have these (along with a few others):
- Default (Matroska's default flag sets this)
- Forced (Matroska's forced flag sets this)
- Dub (Potentially replaceable with an original-language element)
- Original (same, just inverted?)
- Commentary
- Hearing impaired (SDH subtitles)
- Visual impaired (descriptive audio service)

There is also limited support for "dependent" streams, which actually _do_ overlay with another; this is used to add a descriptive-audio stream on top of a regular one in the same language. This apparently comes from broadcast MPEG-TS, and software player support is currently pretty limited.

**Comment by robUx4** [comment]
It's not very clear what the `found matching track(s)` mean in your diagram. IMO that's where the logic is. Or maybe that's a generic chart and the Matroska logic falls into this ? It's interesting though as it shows the complexity of picking the right audio and subtitles. Maybe putting something like that (with the addition of Matroska particularities) in the specs is not feasable as it's too complex.

**Comment by rcombs** [comment]
I intended it to mean "Did any of the tracks in our current candidate group match the criteria from the previous step?".

Perhaps a textual example selection algorithm would be better:

Audio autoselection (occurs once):
1. Create a "candidate audio" list containing audio tracks that match the user's language preferences
2. If the user prefers descriptive-audio tracks, and any candidate audio tracks are descriptive-audio, remove tracks that are not
3. If candidate audio list is empty, fill candidate audio list with tracks matching the content's original language (if known)
4. If candidate audio list is empty, fill candidate audio list with all available audio tracks
5. If some candidate audio tracks are in languages that the user prefers over others in audio, remove the lower-preference tracks from the list
6. If any candidate audio tracks have the "default" flag, remove tracks that do not have the flag from the list
7. If some candidate audio tracks are a better match for the audio output hardware in use than others, remove worse-matching tracks from the list
8. Select the first track out of the remaining list

Subtitle autoselection (occurs after audio autoselection, and any time the selected audio track is changed while no subtitle track has been explicitly chosen):
1. Create a "candidate audio" list containing subtitle tracks that match the user's language preferences
2. If the selected audio track does not match the user's language preferences, skip to step 5
3. If the user prefers that subtitles be displayed automatically when playing audio matching their language preferences, skip to step 5
4. Remove tracks from the "candidate audio" list that do not have the "forced" flag set
5. If there are no candidate tracks, end with no subtitle track selected
6. If some candidate subtitle tracks are in languages that the user prefers over others in subtitles, remove the lower-preference tracks from the list
7. If the user prefers SDH tracks, and any are available, remove candidates that are not SDH
8. If the user prefers _non_-SDH tracks, and any are available, remove candidates that _are_ SDH
9. If any candidate audio tracks have the "default" flag, remove tracks that do not have the flag from the list
10. If some candidate subtitle tracks are in text-based formats and others are in image-based formats, remove the image-based tracks from the list
11. Select the first track out of the remaining list

This is slightly different from the example from the diagram; it handles a couple additional cases (in particular, preferring text-based subtitles over image-based ones when all else is equal, since text-based subtitles don't suffer from bitmap scaling). I'm also not quite positive where the descriptive-audio handling should go in the algorithm, and it might be worth having explicit handling for the "unknown language" case (in this example the user can add it on the end of their preference list). The spec doesn't have to be completely exhaustive on this topic, though. If the spec is going to contain any advice on how to auto-select streams at all, I'd suggest the algorithm be placed in a non-normative section, and that players be advised that they SHOULD or MAY use an algorithm similar to the provided example, without precluding any additional adjustments that a player might want to make.
