### ISSUE TITLE
Why is the Info element multiple?

### ISSUE THREAD

**Issue by hubblec4** [ietf-wg-cellar/matroska-specification#436]
The top-level element 'Info' is a multiple one, and so I can/could set twice or more a TimestampScale element with different values.
Also the SegementUID can then be set multiple times.

**Comment by robUx4** [comment]
The `SegmentUID` has a `maxOccurs` of 1 so it must not be set multiple times.

The Info doesn't have a `maxOccurs` because it is also `recurring`. On the other hand Chapters have `recurring` but also a `maxOccurs`. So we should fix one or the other. That also relates to solving #435.

The EBML spec says this:
> If a Master Element contains more occurrences of a Child Master Element than permitted according to the maxOccurs and recurring attributes of the definition of that Element, then the occurrences in addition to maxOccurs MAY be ignored.

So as long as recurring is set, the maxOccurs doesn't matter. All similar element in the parent are considered a copy of the same content. Whichever has a valid CRC can be used (as it's also encouraged to use a CRC for recurring elements). So there cannot be different values or the file is broken.

To avoid confusion I think we should avoid mixing `maxOccurs` and `recurring` on the same elements.

**Comment by hubblec4** [comment]
> The SegmentUID has a maxOccurs of 1 so it must not be set multiple times.
I don't mean the SegmentUID element it self, when you have multiple `Info` elements and there you can set one SegmentUID but with a different value.

I think I understand the "recurring" attribute a bit better now. The "multiple" attribute is there because the element can be recurring and so we have multiple elements but with the same content.

Yeah that's really confusing.
