### ISSUE TITLE
Should we make ChapterTimeEnd mandatory for ordered chapters ?

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#470]
Right now it's never mandatory but in ordered chapters we need to the have the duration of each parts to play.

**Comment by hubblec4** [comment]
The `ChapterTimeEnd` element must not have the mandatory attribute, because non-ordered chapters never use/need this element.

On the other hand an ordered chapter needs this element to build a duration of these chapter.
Maybe is a hint the best way to force the usage of this element for ordered chapters.

**Comment by robUx4** [comment]
We can make it mandatory for ordered chapters with a change like this
```xml
<documentation lang="en" purpose="usage notes">If the Edition is an ordered edition then this Element is **REQUIRED**.</documentation>
```

**Comment by hubblec4** [comment]
Ok, that is fine to me.
