### ISSUE TITLE
define tags prefixed by underscores

### ISSUE THREAD

**Issue by dericed** [ietf-wg-cellar/matroska-specification#49]
I see some Matroska apps prefixing tag names with underscores but this behavior and associated expectations is not yet in the specification.

For instance

``` xml
<Tags>
   <!-- ... -->
  <Tag>
    <Simple>
      <Name>_STATISTICS_WRITING_APP</Name>
      <String>mkvmerge v8.4.0 ('A better way to fly') 32bit</String>
    </Simple>
    <Simple>
      <Name>_STATISTICS_WRITING_APP</Name>
      <TagLanguage>eng</TagLanguage>
      <String>mkvmerge v8.4.0 ('A better way to fly') 32bit</String>
    </Simple>
    <Simple>
      <Name>_STATISTICS_WRITING_DATE_UTC</Name>
      <String>2015-10-23 09:54:30</String>
    </Simple>
    <Simple>
      <Name>_STATISTICS_WRITING_DATE_UTC</Name>
      <TagLanguage>eng</TagLanguage>
      <String>2015-10-23 09:54:30</String>
    </Simple>
    <Simple>
      <Name>_STATISTICS_TAGS</Name>
      <String>BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES</String>
    </Simple>
    <Simple>
      <Name>_STATISTICS_TAGS</Name>
      <TagLanguage>eng</TagLanguage>
      <String>BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES</String>
    </Simple>
    <Simple>
      <Name>ENCODER</Name>
      <String>Lavc56.41.100 libmp3lame</String>
    </Simple>
  </Tag>
</Tags>

Here `ENCODER` is an `official` tag. The rest (prefixed by underscores) are not represented in the specification but commonly used.
```

**Comment by mbunkus** [comment]
Some background on this. It was I who introduced those tag names with mkvmerge v7.0.0 in 2014. The was in response to a user request for statistical information.

At the time I was considering two approaches: introducing new track header elements and using unofficial tags. My experience with introducing new header elemenets was rather mixed: a lot of players (mostly of the hardware variety) were acting up when they encountered elements they didn't know. For example, introducing `CueDuration` caused several players to skip the whole index causing huge delays on seeking. Additionally introducing new elements always meant having to do and require new releases of libMatroska.

Tags seemed to be a more flexible solution, one we could adapt quicker to new needs.

Therefore I decided to experiment with tags. This wasn't received overly well either, unfortunately, as tags haven't been used that much in the wild and suddenly people started seeing tags everywhere (those from mkvmerge).

Prefixing the names with `_` was intentional in order to differentiate them from officially sanctioned names. However, that was a decision on my part; we hadn't discussed such a prefix on the mailing lists. To be fair back in 2014 the devel mailing lists were mostly dead anyway (there were all of 14 messages in 2014).

I'm fine with stating officially that names prefixed with `_` are unofficial, application-specific names. Similar to how email and HTTP headers starting with `X-` are handled.

**Comment by robUx4** [comment]
Sounds good to me.

**Comment by hubblec4** [comment]
Sounds good to me too,
and after a while playing with the STATISTICS tags, I think it is useful to have a free configurable tagging system for info/values which not saved in the Matroksa EBML structure.
