### ISSUE TITLE
Make Matroska doc completely independant from transported formats

### ISSUE THREAD

**Issue by JeromeMartinez** [ietf-wg-cellar/matroska-specification#679]
WebVTT and DivXTrickTrack are listed in the Matroska core doc.
IMO an element should not be specific to a format, so the core doc should not contain such names, but the Codec doc should say which Matroska elements are mandatory for correct decoding.

**Comment by robUx4** [comment]
All DivX elements are marked as deprecated. They are only listed to avoid reusing the ID and if people ever encounter these ID's.

There is one element related to WebVTT, because that's where it originated, but it is not tied to WebVTT at all:

> A unique string ID to identify the Chapter. For example it is used as the storage for [WebVTT] cue identifier values.

As for elements mandatory for correct decoding "in general", that's all the elements that are mandatory. For particular elements like this one, it should be document in the Codecs Specs for WebVTT that this element is mandatory (in some cases?) for WebVTT. It is currently not the case.

**Comment by robUx4** [comment]
Closing as RFC9559 has been publish and it probably doesn't apply anymore.
