### ISSUE TITLE
TargetType has "PART" twice in the enum values

### ISSUE THREAD

**Issue by hubblec4** [ietf-wg-cellar/matroska-specification#738]
I can remember me that in the past the `label` values was the same like the `enum` vaules.

For example:
`enum`: COLLECTION -> `label`: Collection

Now is the `label`: TargetTypeVaule 70.

TargetTypeValue 70 should be set to the `documentation` -> `usage notes`.

But the question still is, can `enum` values be used? [String element range values](https://github.com/ietf-wg-cellar/matroska-specification/issues/737)

And a second issue is that the `enum` value "PART" occurs twice.
This value can be used if the `TargetTypeValue` value is 40 or 20.

I can not implement an Enum type with duplicated values (Lazarus), and I guess in c++ it is also not possible.

**Comment by robUx4** [comment]
`TargetTypeValue` is not a string value, it's a `uinteger`. It is perfectly OK so use an enum there.

The current libmatroska and libmatroska2 uses these enum values to generate values with the labels from the specs. The names are even the same between the two libraries.

- https://github.com/Matroska-Org/libmatroska/blob/1ec3ab371385d675f4e1b402781741c39f418297/matroska/KaxSemantic.h#L1217
- https://github.com/Matroska-Org/foundation-source/blob/7933debccf1396b2383f074ef1ffe8d71b5e1306/libmatroska2/matroska2/matroska_sem.h#L684

Only the first strings before the / are used for the name of the enum. That's why it works with PART, which is only used one.

`TargetType` is not generated. In C/C++ enum values can't be strings. However, there is an issue with the double usage of `"PART"` there as you mention.

**Comment by hubblec4** [comment]
> TargetTypeValue is not a string value, it's a uinteger. It is perfectly OK so use an enum there.

Yes, of course. I also have not spoken about the `TargetTypeValue`, I mean the `TargetType` element which is a String-Type.

The current table for the `restriction enums` of `TargetType` uses weird names as `label`.
