### ISSUE TITLE
WebM Supported Elements

### ISSUE THREAD

**Issue by complexlogic** [ietf-wg-cellar/matroska-specification#813]
I'm reviewing the [Element Specification](https://matroska.org/technical/elements.html) on the Matroska website. It says that the Attachments element and its children are supported in WebM. My understanding is that Attachments are not supported in WebM.

When I look at the [EBML schema document](https://github.com/ietf-wg-cellar/matroska-specification/blob/master/ebml_matroska.xml), the webm extension element is not included in Attachments. Is there a problem with the site rendering?

**Comment by complexlogic** [comment]
I understand that. However, the [Element Specification on the Matroska website](https://matroska.org/technical/elements.html) has a column for WebM, and it's generated from a file hosted in this repo.

**Comment by robUx4** [comment]
Yes, the file is hosted here and is used to generate some code in various places. So that is the right place to fix it, even if it doesn't make any difference to the files generated in IETF documents.

It seems that indeed attachment is not supported: https://www.webmproject.org/docs/container/

But the ebml_matroska.xml file is correct. We use `<extension type="webmproject.org" webm="1"/>` to signal an element is included in WebM. The generator for the website is bogus as it does the opposite. Since 8998fd8836c399ba786c55c33e57a5bf8244ea84 we inverted the flags to mark elements as part of WebM.

cc @mbunkus

**Comment by robUx4** [comment]
The issue should be reported in https://github.com/Matroska-Org/infrastructure
